### ISSUE TITLE
Logo Tipo

### ISSUE THREAD

**Issue by henriqueCMarques** [ICEI-PUCMinas-PSG-SI-TI/sg_n_2022-1-arquitetando#14]
Não estou conseguindo fazer o upload do logo tipo do trabalho no diretório - /codigo/Site - Arquitetando/images - Aparece a mensagem "Something went really wrong, and we can’t process that file."

![Sem nome (130 × 40 px)](https://user-images.githubusercontent.com/104331565/170349058-3e12a738-f91a-478e-9377-ceda8efb9f87.png)

**Comment by apoliveirapuc** [comment]
Magicamente funcionou
